# 固定音频标准（不能改）
SAMPLE_RATE = 16000
CHANNELS = 1
FORMAT = 16
CHUNK = 1024

# VAD参数
VAD_AGGRESSIVENESS = 2

# Whisper模型
WHISPER_MODEL_SIZE = "base"  # 小模型，速度快
WHISPER_LANGUAGE = "zh"
WHISPER_BEAM_SIZE = 5
WHISPER_TEMPERATURE = 0.0

# 指令映射
COMMAND_MAP = {}